# userservice-dev.yml

info:
  environment: "Development"

configclient:
  message: "Updated Welcome Message 1"
  database:
    url: "jdbc:mysql://localhost:3306/userdb_dev"
    username: "devuser"
    password: "devpassword"
